# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 20:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='author',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='notification_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='auto_hide_seconds',
            field=models.IntegerField(blank=True, default=0, help_text='Automatically hide after this number of seconds, 0 meaning no auto-hide', verbose_name='Timeout'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='display_mode',
            field=models.CharField(choices=[('notification', 'HTML notification'), ('modal', 'Blocking (modal) window'), ('system', 'System notification'), ('banner', 'Screen-wide banner')], default='notification', help_text='System notifications can be hidden by users.', max_length=20, verbose_name='Display mode'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='icon',
            field=models.FileField(blank=True, default=None, help_text='Not used yet', max_length=255, null=True, upload_to='notification_icons', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Only active notifications will be displayed.', verbose_name='Is active?'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='repeat_count',
            field=models.IntegerField(blank=True, db_index=True, default=1, help_text='Display count (0 meaning that the notification will always be displayed)', verbose_name='Repeat count'),
        ),
    ]
